version: '3.1'
services:
    server:
        ports:
            - "80:80"
            - "443:443"
        build:
            context: /enviroments/devshop/images/
            dockerfile: "phpsb"
        links:
            - mysql
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
        volumes:
            - /enviroments/devshop/www:/var/www
            - /enviroments/devshop/apache2/sites-available:/etc/apache2/sites-available
    mysql:
        image: mysql:8.0.12
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - /enviroments/devshop/mysql:/var/lib/mysql
            - /enviroments/devshop/dump.sql:/home/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: 1
        networks:
            testing_net:
                ipv4_address: 172.28.1.2
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
